package model;
// Generated Nov 11, 2017 10:38:04 AM by Hibernate Tools 4.3.1



/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer idCompany;
     private String nameCompany;
     private String addressCompany;

    public Company() {
    }

    public Company(String nameCompany, String addressCompany) {
       this.nameCompany = nameCompany;
       this.addressCompany = addressCompany;
    }
   
    public Integer getIdCompany() {
        return this.idCompany;
    }
    
    public void setIdCompany(Integer idCompany) {
        this.idCompany = idCompany;
    }
    public String getNameCompany() {
        return this.nameCompany;
    }
    
    public void setNameCompany(String nameCompany) {
        this.nameCompany = nameCompany;
    }
    public String getAddressCompany() {
        return this.addressCompany;
    }
    
    public void setAddressCompany(String addressCompany) {
        this.addressCompany = addressCompany;
    }




}


