package model;
// Generated Nov 11, 2017 10:38:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Donhang generated by hbm2java
 */
public class Donhang  implements java.io.Serializable {


     private Integer idDonHang;
     private Date ngayDatHang;
     private Date ngayNhanHang;
     private Boolean trangThai;
     private int idUser;

    public Donhang() {
    }

	
    public Donhang(int idUser) {
        this.idUser = idUser;
    }
    public Donhang(Date ngayDatHang, Date ngayNhanHang, Boolean trangThai, int idUser) {
       this.ngayDatHang = ngayDatHang;
       this.ngayNhanHang = ngayNhanHang;
       this.trangThai = trangThai;
       this.idUser = idUser;
    }
   
    public Integer getIdDonHang() {
        return this.idDonHang;
    }
    
    public void setIdDonHang(Integer idDonHang) {
        this.idDonHang = idDonHang;
    }
    public Date getNgayDatHang() {
        return this.ngayDatHang;
    }
    
    public void setNgayDatHang(Date ngayDatHang) {
        this.ngayDatHang = ngayDatHang;
    }
    public Date getNgayNhanHang() {
        return this.ngayNhanHang;
    }
    
    public void setNgayNhanHang(Date ngayNhanHang) {
        this.ngayNhanHang = ngayNhanHang;
    }
    public Boolean getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Boolean trangThai) {
        this.trangThai = trangThai;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }




}


