package model;
// Generated Nov 11, 2017 10:38:04 AM by Hibernate Tools 4.3.1



/**
 * Groupuser generated by hbm2java
 */
public class Groupuser  implements java.io.Serializable {


     private Integer idGroupUser;
     private String nameGroup;

    public Groupuser() {
    }

    public Groupuser(String nameGroup) {
       this.nameGroup = nameGroup;
    }
   
    public Integer getIdGroupUser() {
        return this.idGroupUser;
    }
    
    public void setIdGroupUser(Integer idGroupUser) {
        this.idGroupUser = idGroupUser;
    }
    public String getNameGroup() {
        return this.nameGroup;
    }
    
    public void setNameGroup(String nameGroup) {
        this.nameGroup = nameGroup;
    }




}


